name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build Web Interface
      run: npm run build
      env:
        CI: true
    - name: Install Pods
      run: cd ./ios && pod install
    - name: Build
      run: cd ./ios && xcodebuild build -workspace Plugin.xcworkspace -scheme Plugin -sdk iphoneos

